export const ADDRESS_DETAILS_REQUEST = 'ADDRESS_DETAILS_REQUEST'
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS'
export const ADDRESS_DETAILS_FAIL = 'ADDRESS_DETAILS_FAIL'

export const LIST_ADDRESS_REQUEST = 'LIST_ADDRESS_REQUEST'
export const LIST_ADDRESS_SUCCESS = 'LIST_ADDRESS_SUCCESS'
export const LIST_ADDRESS_FAIL = 'LIST_ADDRESS_FAIL'

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL' 

export const ADD_NEW_ADDRESS_REQUEST = 'ADD_NEW_ADDRESS_REQUEST'
export const ADD_NEW_ADDRESS_SUCCESS = 'ADD_NEW_ADDRESS_SUCCESS'
export const ADD_NEW_ADDRESS_FAIL = 'ADD_NEW_ADDRESS_FAIL'


