export const LIST_ADDRESS_REQUEST = 'LIST_ADDRESS_REQUEST'
export const LIST_ADDRESS_SUCCESS = 'LIST_ADDRESS_SUCCESS'
export const LIST_ADDRESS_FAIL = 'LIST_ADDRESS_FAIL'

export const ADD_NEW_ADDRESS_REQUEST = 'ADD_NEW_ADDRESS_REQUEST'
export const ADD_NEW_ADDRESS_SUCCESS = 'ADD_NEW_ADDRESS_SUCCESS'
export const ADD_NEW_ADDRESS_FAIL = 'ADD_NEW_ADDRESS_FAIL'


