export const DISH_CREATE_REQUEST = 'DISH_CREATE_REQUEST'
export const DISH_CREATE_SUCCESS = 'DISH_CREATE_SUCCESS'
export const DISH_CREATE_FAIL = 'DISH_CREATE_FAIL'
export const DISH_CREATE_RESET = 'DISH_CREATE_RESET'

export const DISH_LIST_REQUEST = 'DISH_LIST_REQUEST'
export const DISH_LIST_SUCCESS = 'DISH_LIST_SUCCESS'
export const DISH_LIST_FAIL = 'DISH_LIST_FAIL'
