export const DISH_CREATE_REQUEST = 'DISH_CREATE_REQUEST'
export const DISH_CREATE_SUCCESS = 'DISH_CREATE_SUCCESS'
export const DISH_CREATE_FAIL = 'DISH_CREATE_FAIL'
export const DISH_CREATE_RESET = 'DISH_CREATE_RESET'

export const DISH_LIST_REQUEST = 'DISH_LIST_REQUEST'
export const DISH_LIST_SUCCESS = 'DISH_LIST_SUCCESS'
export const DISH_LIST_FAIL = 'DISH_LIST_FAIL'

export const DISH_DETAILS_REQUEST = 'DISH_DETAILS_REQUEST'
export const DISH_DETAILS_SUCCESS = 'DISH_DETAILS_SUCCESS'
export const DISH_DETAILS_FAIL = 'DISH_DETAILS_FAIL'

export const DISH_EDIT_REQUEST = 'DISH_EDIT_REQUEST'
export const DISH_EDIT_SUCCESS = 'DISH_EDIT_SUCCESS'
export const DISH_EDIT_FAIL = 'DISH_EDIT_FAIL'
export const DISH_EDIT_RESET = 'DISH_EDIT_RESET'
