export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const PREPARE_ORDER_REQUEST = 'PREPARE_ORDER_REQUEST'
export const PREPARE_ORDER_SUCCESS = 'PREPARE_ORDER_SUCCESS'
export const PREPARE_ORDER_FAIL = 'PREPARE_ORDER_FAIL'
export const PREPARE_ORDER_RESET = 'PREPARE_ORDER_RESET'

export const ORDER_OUT_FOR_DELIVERY_REQUEST = 'ORDER_OUT_FOR_DELIVERY_REQUEST'
export const ORDER_OUT_FOR_DELIVERY_SUCCESS = 'ORDER_OUT_FOR_DELIVERY_SUCCESS'
export const ORDER_OUT_FOR_DELIVERY_FAIL = 'ORDER_OUT_FOR_DELIVERY_FAIL'
export const ORDER_OUT_FOR_DELIVERY_RESET = 'ORDER_OUT_FOR_DELIVERY_RESET'

export const DELIVER_ORDER_REQUEST = 'DELIVER_ORDER_REQUEST'
export const DELIVER_ORDER_SUCCESS = 'DELIVER_ORDER_SUCCESS'
export const DELIVER_ORDER_FAIL = 'DELIVER_ORDER_FAIL'
export const DELIVER_ORDER_RESET = 'DELIVER_ORDER_RESET'

export const CONFIRM_ORDER_REQUEST = 'CONFIRM_ORDER_REQUEST'
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS'
export const CONFIRM_ORDER_FAIL = 'CONFIRM_ORDER_FAIL'
export const CONFIRM_ORDER_RESET = 'CONFIRM_ORDER_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
