export const LIST_RESTAURANT_REQUEST = 'LIST_RESTAURANT_REQUEST'
export const LIST_RESTAURANT_SUCCESS = 'LIST_RESTAURANT_SUCCESS'
export const LIST_RESTAURANT_FAIL = 'LIST_RESTAURANT_FAIL'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST'
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS'
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL'

export const RESTAURANT_EDIT_REQUEST = 'RESTAURANT_EDIT_REQUEST'
export const RESTAURANT_EDIT_SUCCESS = 'RESTAURANT_EDIT_SUCCESS'
export const RESTAURANT_EDIT_FAIL = 'RESTAURANT_EDIT_FAIL'
export const RESTAURANT_EDIT_RESET = 'RESTAURANT_EDIT_RESET'